package tachiyomi.domain.anime.model

data class AnimeTitleUpdate(
    val id: Long,
    val source: Long? = null,
    val url: String? = null,
    val title: String? = null,
    val displayName: String? = null,
    val originalTitle: String? = null,
    val country: String? = null,
    val studio: String? = null,
    val producer: String? = null,
    val director: String? = null,
    val writer: String? = null,
    val year: String? = null,
    val duration: String? = null,
    val description: String? = null,
    val genre: List<String>? = null,
    val status: Long? = null,
    val thumbnailUrl: String? = null,
    val favorite: Boolean? = null,
    val initialized: Boolean? = null,
    val lastUpdate: Long? = null,
    val dateAdded: Long? = null,
    val episodeFlags: Long? = null,
    val coverLastModified: Long? = null,
    val version: Long? = null,
    val notes: String? = null,
)
