name: Release
on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  get_tag:
    name: Extract tag name
    runs-on: 'ubuntu-24.04'
    outputs:
      tag: ${{ steps.extract.outputs.tag }}

    steps:
      - name: Get tag name
        id: extract
        run: echo "tag=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_OUTPUT

  build:
    name: Build (FOSS)
    runs-on: ubuntu-24.04
    needs: get_tag

    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - name: Set up JDK
        uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5.2.0
        with:
          java-version-file: .github/.java-version
          distribution: temurin

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@0723195856401067f7a2779048b490ace7a47d7c # v5.0.2

      - name: Build
        run: ./gradlew assembleFoss -Penable-updater

      - name: Sign APK
        uses: r0adkll/sign-android-release@f30bdd30588842ac76044ecdbd4b6d0e3e813478
        with:
          releaseDirectory: app/build/outputs/apk/foss
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: '35.0.1'

      - name: Rename APK
        run: |
          set -e

          mv app/build/outputs/apk/foss/app-universal-foss-unsigned-signed.apk mihon-${{ needs.get_tag.outputs.tag }}-foss.apk

      - name: Upload APK
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: mihon
          path: mihon-${{ needs.get_tag.outputs.tag }}-foss.apk

  release:
    name: Create GitHub Release
    runs-on: ubuntu-24.04
    needs: [get_tag, build]
    permissions:
      contents: write

    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          merge-multiple: true

      - name: Delete all artifacts
        uses: geekyeggo/delete-artifact@f275313e70c08f6120db482d7a6b98377786765b # v5.1.0
        with:
          failOnError: false
          name: mihon

      - name: Create GitHub Release
        uses: softprops/action-gh-release@1853d73993c8ca1b2c9c1a7fede39682d0ab5c2a # v2.5.3
        with:
          tag_name: ${{ needs.get_tag.outputs.tag }}
          name: Mihon ${{ needs.get_tag.outputs.tag }}
          body: |
            Release ${{ needs.get_tag.outputs.tag }}
          files: mihon-${{ needs.get_tag.outputs.tag }}-foss.apk
          draft: true
          prerelease: false
